services:
  db:
    image: docker.io/library/postgres:17-alpine
    container_name: postgres_sql_srv
    secrets:
      - mypassword
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/mypassword
      POSTGRES_DB: Flowster
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: docker.io/dpage/pgadmin4:9.15
    container_name: pgadmin
    secrets:
      - mypassword
    ports:
      - 5050:8080
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.int
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/mypassword
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_LISTEN_PORT: 8080
    networks:
      - db-network
    depends_on:
      db:
        condition: service_healthy
        
volumes:
  pgdata:
  pgadmindata:
networks:
  db-network:
    driver: bridge
secrets:
  mypassword:
    file: ./top-secret.txt

